sparql_query: [queries\BOPTest_query_os_c_2b_zone_pre_heat_cool_com_gBldg.rq, queries\BOPTest_query_os_c_2b_zone_pre_heat_cool_com_gZone.rq] #path to interface query.
graph_path: testcase_bestest_hydronic_heat_pump\bestest_hydronic_heat_pump.ttl #path to each test case Brick graph.
baseline_path: testcase_bestest_hydronic_heat_pump\results_os_c_2b_zone_pre_heat_cool_com\default_scenario\baseline.csv #path to baseline csv file

price_identifier: PriceElectricPowerHighlyDynamic #identifier to get the price signal.

hvac_mode_identifier: oveHeaPumY_u #identifier to get control signal (for test cases in which HVAC mode estimation is based on a single control signal). 
heat_signal_identifier: #identifier to get heating control signal (for test cases which have a heating control signal).
cool_signal_identifier: #identifier to get cooling control signal (for test cases which have a cooling control signal).

occ_flex_set_temp_min: 18 # min temperature setpoint during df
occ_flex_set_temp_max: 27 # max temperature setpoint during df
non_occ_flex_set_temp_min: 15  # min temperature setpoint during df
non_occ_flex_set_temp_max: 30  # max temperature setpoint during df

shift_adjust: 2 #adjustment factor for the temperature setpoint during shift 
shift_horizon_time: 12 # hours ahead to start shift period 
shift_dev_threshold: 3 #shift threshold for zone temperature deviation from effective setpoint

peak_demand_diff_error_min: 500 # minimum allowable difference between peak and current demand
deadband_peak_demand_diff_error_min: 5 #deadband value for minimum allowable difference between peak and current current 

hands_off_zone: [] #list of zones that should not execute DF control