sparql_query: [queries\BOPTest_query_os_c_1b2a_zone_temp_adj_perform_ratch_pre_heat_cool_sim_gBldg.rq, queries\BOPTest_query_os_c_1b2a_zone_temp_adj_perform_ratch_pre_heat_cool_sim_gZone.rq] #path to interface query.
graph_path: testcase_singlezone_commercial_hydronic\singlezone_commercial_hydronic.ttl #path to each test case Brick graph.
baseline_path: testcase_singlezone_commercial_hydronic\results_os_c_1b2a_zone_temp_adj_perform_ratch_pre_heat_cool_sim\default_scenario\baseline.csv #path to baseline csv file

price_identifier:  PriceElectricPowerHighlyDynamic #identifier to get the price signal.

hvac_mode_identifier: 'ovePum_u' #identifier to get control signal (for test cases in which HVAC mode estimation is based on a single control signal). #lower bound on the range of permitted values of a temperature setpoint.
heat_signal_identifier: #identifier to get heating control signal (for test cases which have a heating control signal).
cool_signal_identifier: #identifier to get cooling control signal (for test cases which have a cooling control signal).

occ_flex_set_temp_min: 18 # min temperature setpoint during df
occ_flex_set_temp_max: 27 # max temperature setpoint during df
non_occ_flex_set_temp_min: 15  # min temperature setpoint during df
non_occ_flex_set_temp_max: 30  # max temperature setpoint during df

shed_initial_adjust: 1 #adjustment factor for the temperature setpoint during first shed 
shed_delta_ratchet: 0.5 #incremental delta for ratcheting zone temperature setpoint
shed_dev_threshold: 0.5 #shed threshold for zone temperature deviation from effective setpoint

demand_decrease_cap: 50000 #objective electrical demand decrease (DDcap)
demand_decrease_error_min: 500 #minimum allowable difference between DDcap and DDbldg

shift_adjust: 2 #adjustment factor for the temperature setpoint during shift 
shift_horizon_time: 3 # hours ahead to start shift period 
shift_dev_threshold: 3 #shift threshold for zone temperature deviation from effective setpoint

hands_off_zone: [] #list of zones that should not execute DF control