SELECT ?zone ?zone_temp_point ?set_temp_min_point ?set_temp_max_point ?occ_sensor_point ?zone_set_temp_heat_point
 ?zone_set_temp_cool_point ?zone_set_temp_point ?vav_damper_set_point ?vav_damper_set_point ?vav_discharge_temp_point
?vav_reheat_command_point
WHERE {
    ?zone a brick:Zone ;
    brick:hasPoint ?TZon, ?TSetMin, ?TSetMax, ?TSetHeaZon, ?TSetCooZon, ?TSetZon, ?Occ .
    
    ?TZon a brick:Zone_Air_Temperature_Sensor ;
        ref:hasExternalReference/ref:hasTimeseriesId ?zone_temp_point .

    OPTIONAL {
    ?TSetMin a brick:Min_Air_Temperature_Setpoint ;
        ref:hasExternalReference/ref:hasTimeseriesId ?set_temp_min_point .}

    OPTIONAL {
    ?TSetMax a brick:Max_Air_Temperature_Setpoint ;
        ref:hasExternalReference/ref:hasTimeseriesId ?set_temp_max_point .}

    OPTIONAL {
    ?Occ a brick:Occupancy_Sensor ;
        ref:hasExternalReference/ref:hasTimeseriesId ?occ_sensor_point .}

    OPTIONAL {
    ?TSetHeaZon a brick:Zone_Air_Heating_Temperature_Setpoint;
        ref:hasExternalReference/ref:hasTimeseriesId ?zone_set_temp_heat_point .}

    OPTIONAL {
    ?TSetCooZon a brick:Zone_Air_Cooling_Temperature_Setpoint;
        ref:hasExternalReference/ref:hasTimeseriesId ?zone_set_temp_cool_point .}

    OPTIONAL {
    ?TSetZon a brick:Zone_Air_Temperature_Setpoint;
        ref:hasExternalReference/ref:hasTimeseriesId ?zone_set_temp_point .}

    OPTIONAL {
    ?vav brick:feeds ?zone ;
         brick:hasPoint ?Vav_DamSet .
    ?Vav_DamSet a brick:Damper_Position_Setpoint;
        ref:hasExternalReference/ref:hasTimeseriesId ?vav_damper_set_point .}

    OPTIONAL {
    ?vav brick:feeds ?zone ;
         brick:hasPoint ?Vav_DamSet, ?Vav_DisTemp.
    ?Vav_DisTemp a brick:Discharge_Air_Temperature_Sensor;
        ref:hasExternalReference/ref:hasTimeseriesId ?vav_discharge_temp_point .}

    OPTIONAL {
    ?vav brick:feeds ?zone ;
         brick:hasPoint ?Vav_ReheatCmd .
    ?Vav_ReheatCmd a brick:Valve_Command;
        ref:hasExternalReference/ref:hasTimeseriesId ?vav_reheat_command_point .}

}
    GROUP BY ?zone